# fly.toml app configuration file generated for spring-dust-7208 on 2023-09-25T19:52:25+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "spring-dust-7208"
primary_region = "ams"

[build]

[http_service]
  internal_port = 5005
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
